### PR TITLE
optimize images

### PR DESCRIPTION
**Pull request by marcobiedermann**
Optimize images without losing any quality using [ImageOptim](https://imageoptim.com/).
Saves over 5.7 MB

una-images

### CODE REVIEW

**Comment by frog79** [comment]
Hi. Saw that there was also a gulp. https://www.npmjs.com/package/gulp-imageoptim

Would IT not be better to change gulp.js to imageoptim ?

**Comment by frog79** [comment]
gulp = require('gulp');
var imageOptim = require('gulp-imageoptim');
 
 
gulp.task('images', function() {
    return gulp.src('src/images/**/*')
        .pipe(imageOptim.optimize())
        .pipe(gulp.dest('build/images'));
});

**Comment by una** [comment]
@frog79 and @marcobiedermann -- the imagemin task is already implemented: https://github.com/una/una.github.io/blob/master/gulpfile.js#L77

So the images being served in dist (which are gitignored) are being processed with Imagemin already in the build process

**Comment by marcobiedermann** [comment]
@frog79 @una Yes you are right. I optimized the source files. The only benefit would be that the gulp task might be a bit faster. Still the output will be the same. So this is more of a minor improvement ;)

**Comment by frog79** [comment]
Hi ! Excellent. But does marcos Discovery actually change with that significant size diffrences
If IT is processed with gulp imageoptim vs gulp imagemin ? 

Is there any difference? And what is the performance eg image looks? 

Sorry if i could i would. Just trying out !

**Comment by frog79** [comment]
Marco. Was source files output from min already performed or raw images? Many thanks for your guys open source contributions ! Respect

**Pull request closed without merging**
